### ISSUE TITLE
support for webpack newer than 1.x

### ISSUE THREAD

**Issue by volth** [tailhook/khufu#1]
I got the idea that ```loader.js``` should overwrite ```index.js``` to work with ```webpack 2+``` but it would be nice to have a less hacky way to get ```khufu``` work with the newer ```webpack``` than fix something inside ```./node_packages``` after each ```npm i```

**Comment by tailhook** [comment]
Hi,

We use webpack 2.0 since it was beta in [verwalter](https://github.com/tailhook/verwalter/tree/master/frontend). If I remember correctly you need to add `webpackLoader` to `mainFields` in `webpack.config.js`, like this:
```
    resolveLoader: {
        mainFields: ["webpackLoader", "main"],
    },
```
